In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("6-bank_customers.csv")

In [3]:
df.head()

,age,job_satisfaction,balance,duration_last_call,num_contacts_last_month,has_housing_loan,has_personal_loan,communication_type,days_since_last_contact,campaign_response_score,subscribed
0,-0.377957,1.043895,1.043494,-0.101838,-1.617442,0.402713,0.913601,-0.067192,0.175471,-1.049646,0
1,-0.325259,1.276263,-0.686123,-2.463205,-0.489426,-0.240715,-1.469496,1.006633,-0.833692,0.957744,0
2,0.739019,-0.600903,-0.177294,1.335714,-0.817332,-0.790047,1.457365,-0.218981,0.878643,-1.257740,0
3,0.474312,-1.103002,1.189936,-0.800186,0.912377,-0.406451,-1.130950,1.985111,1.379029,1.041768,1
4,0.927365,1.114796,0.080284,1.261064,0.761179,0.921563,0.440832,0.184645,-1.567739,-0.142107,1


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      1000 non-null   float64
 1   job_satisfaction         1000 non-null   float64
 2   balance                  1000 non-null   float64
 3   duration_last_call       1000 non-null   float64
 4   num_contacts_last_month  1000 non-null   float64
 5   has_housing_loan         1000 non-null   float64
 6   has_personal_loan        1000 non-null   float64
 7   communication_type       1000 non-null   float64
 8   days_since_last_contact  1000 non-null   float64
 9   campaign_response_score  1000 non-null   float64
 10  subscribed               1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [8]:
X = df.drop("subscribed",axis=1)
y = df["subscribed"]

In [9]:
y

0      0
1      0
2      0
3      1
4      1
      ..
995    0
996    1
997    1
998    1
999    0
Name: subscribed, Length: 1000, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=15,train_size=0.3)

In [2]:
from sklearn.linear_model import LogisticRegression

In [13]:
logistic = LogisticRegression()
logistic.fit(X_train,y_train)
y_pred = logistic.predict(X_test)

In [14]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [16]:
score = accuracy_score(y_pred,y_test)
print("score: ",score)
print(classification_report(y_pred,y_test))
print("Confusion Matrix: \n", confusion_matrix(y_pred,y_test))

score:  0.92
              precision    recall  f1-score   support

           0       0.97      0.88      0.92       380
           1       0.87      0.97      0.92       320

    accuracy                           0.92       700
   macro avg       0.92      0.92      0.92       700
weighted avg       0.93      0.92      0.92       700

Confusion Matrix: 
 [[333  47]
 [  9 311]]


In [17]:
#hyperparamater tuning

In [3]:
model = LogisticRegression()

In [33]:
penalty = ["l1","l2","elasticnet"]
c_values = [100,50,10,5,1,0.5,0,1,0.05,0.01]
solver = ["newton-cg","lbfgs","liblinear","sag","saga","newton-cholesky"]

In [34]:
params = dict(penalty = penalty, C = c_values, solver = solver)

In [35]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 50, 10, 5, 1, 0.5, 0, 1, 0.05, 0.01],
 'solver': ['newton-cg',
  'lbfgs',
  'liblinear',
  'sag',
  'saga',
  'newton-cholesky']}

In [36]:
#grid search cv

In [37]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold

In [38]:
cv = StratifiedKFold()

In [39]:
grid = GridSearchCV(estimator=model,param_grid=params, cv=cv, scoring="accuracy",n_jobs=-1)

In [40]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 50, 10, 5, 1, 0.5, 0, 1, 0.05, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [41]:
grid.fit(X_train,y_train)

/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/o

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 50, 10, 5, 1, 0.5, 0, 1, 0.05, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [42]:
grid.best_params_

{'C': 0.05, 'penalty': 'l1', 'solver': 'liblinear'}

In [43]:
 grid.best_score_

0.9266666666666667

In [44]:
y_pred = grid.predict(X_test)

In [45]:
score = accuracy_score(y_pred,y_test)
print("score: ",score)
print(classification_report(y_pred,y_test))
print("Confusion Matrix: \n", confusion_matrix(y_pred,y_test))

score:  0.92
              precision    recall  f1-score   support

           0       0.98      0.87      0.92       386
           1       0.86      0.98      0.92       314

    accuracy                           0.92       700
   macro avg       0.92      0.93      0.92       700
weighted avg       0.93      0.92      0.92       700

Confusion Matrix: 
 [[336  50]
 [  6 308]]


In [46]:
#random search cv

In [47]:
from sklearn.model_selection import RandomizedSearchCV

In [48]:
model = LogisticRegression()

In [49]:
randomcv = RandomizedSearchCV(estimator=model, param_distributions=params,cv=5, n_iter=10, scoring="accuracy")

In [50]:
randomcv.fit(X_train,y_train)

/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/o

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 50, 10, 5, 1, 0.5, 0, 1,
                                              0.05, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag', 'saga',
                                                   'newton-cholesky']},
                   scoring='accuracy')

In [51]:
randomcv.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.05}

In [52]:
randomcv.best_score_

0.9066666666666666

In [53]:
y_pred = randomcv.predict(X_test)

In [55]:
score = accuracy_score(y_pred,y_test)
print("score: ",score)
print(classification_report(y_pred,y_test))
print("Confusion Matrix: \n", confusion_matrix(y_pred,y_test))

score:  0.9157142857142857
              precision    recall  f1-score   support

           0       0.98      0.87      0.92       387
           1       0.85      0.98      0.91       313

    accuracy                           0.92       700
   macro avg       0.92      0.92      0.92       700
weighted avg       0.92      0.92      0.92       700

Confusion Matrix: 
 [[335  52]
 [  7 306]]
