In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [3]:
df = pd.read_csv("7-cyber_attack_data.csv")

In [4]:
df.head()

,src_packet_rate,dst_packet_rate,avg_payload_size,connection_duration,tcp_flag_count,avg_interarrival_time,failed_login_attempts,unusual_port_activity_score,session_entropy,avg_response_delay,attack_type
0,-1.286132,-0.648334,1.044115,-0.469715,0.789859,-0.083727,-1.647309,-1.316412,1.011910,-0.898063,2
1,-0.222224,2.083232,1.191114,-1.354527,-0.956992,1.696028,-1.070406,0.981403,-1.628798,1.377594,0
2,-0.431963,0.375745,-1.370334,0.819214,0.345243,1.389447,-1.904130,1.292602,0.925545,0.232705,0
3,-0.912633,0.986988,-0.690042,2.014628,-0.442260,0.590347,-1.819353,1.560938,0.823755,0.517762,0
4,-0.367056,1.667892,0.879172,2.214276,1.846338,-0.894047,1.543838,0.931103,-1.015210,1.061845,1


In [5]:
df.columns

Index(['src_packet_rate', 'dst_packet_rate', 'avg_payload_size',
       'connection_duration', 'tcp_flag_count', 'avg_interarrival_time',
       'failed_login_attempts', 'unusual_port_activity_score',
       'session_entropy', 'avg_response_delay', 'attack_type'],
      dtype='object')

In [ ]:
# src_packet_rate -> Source-side packet transmission rate
# dst_packet_rate -> Destination-side packet reception rate
# avg_payload_size -> Average size of payload in packets
# connection_duration -> Duration of the connection (in seconds)
# tcp_flag_count -> Number of TCP flag occurrences
# avg_interarrival_time -> Time between packet arrivals
# failed_login_attempts -> Number of failed login attempts
# unusual_port_activity_score -> Score representing unusual port usage
# session_entropy -> Entropy of session behavior (for anomaly detection)
# avg_response_delay -> Average delay in server response (in ms)
# attack_type -> 0 = Normal, 1 = DDoS, 2 = Port Scan

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   src_packet_rate              1000 non-null   float64
 1   dst_packet_rate              1000 non-null   float64
 2   avg_payload_size             1000 non-null   float64
 3   connection_duration          1000 non-null   float64
 4   tcp_flag_count               1000 non-null   float64
 5   avg_interarrival_time        1000 non-null   float64
 6   failed_login_attempts        1000 non-null   float64
 7   unusual_port_activity_score  1000 non-null   float64
 8   session_entropy              1000 non-null   float64
 9   avg_response_delay           1000 non-null   float64
 10  attack_type                  1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [9]:
X = df.drop("attack_type",axis=1)
y = df["attack_type"]

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.3,random_state=15)

In [12]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [13]:
y_pred

array([2, 0, 0, 0, 2, 0, 1, 1, 2, 0, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0,
       0, 1, 1, 1, 1, 2, 1, 2, 1, 0, 0, 2, 2, 2, 1, 2, 2, 0, 2, 1, 0, 2,
       1, 1, 2, 0, 0, 0, 2, 0, 1, 2, 0, 2, 1, 2, 2, 1, 0, 0, 0, 2, 1, 1,
       1, 0, 2, 0, 2, 0, 2, 1, 0, 0, 0, 1, 2, 2, 1, 0, 0, 2, 2, 0, 2, 2,
       1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       2, 1, 2, 1, 0, 1, 2, 0, 0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 2, 1, 0, 2,
       2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 1, 1,
       0, 0, 1, 1, 1, 2, 2, 0, 0, 2, 2, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 2,
       0, 2, 2, 0, 2, 1, 1, 1, 2, 1, 0, 1, 0, 1, 1, 2, 0, 2, 1, 2, 1, 0,
       1, 2, 0, 2, 1, 0, 1, 0, 2, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0,
       2, 0, 2, 1, 2, 1, 0, 0, 1, 1, 2, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1,
       0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0, 0, 1, 2, 1, 1, 2, 0,
       2, 0, 1, 0, 0, 2, 0, 1, 2, 2, 2, 2, 0, 2, 1, 0, 0, 0, 2, 1, 2, 1,
       2, 1, 0, 0, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 0,

In [15]:
score = accuracy_score(y_pred,y_test)
print("score: ",score)
print(classification_report(y_pred,y_test))
print("Confusion Matrix: \n", confusion_matrix(y_pred,y_test))

score:  0.7785714285714286
              precision    recall  f1-score   support

           0       0.84      0.80      0.82       234
           1       0.75      0.76      0.76       234
           2       0.75      0.77      0.76       232

    accuracy                           0.78       700
   macro avg       0.78      0.78      0.78       700
weighted avg       0.78      0.78      0.78       700

Confusion Matrix: 
 [[188  14  32]
 [ 29 179  26]
 [  7  47 178]]


In [16]:
penalty = ["l1","l2","elasticnet"]
c_values = [100,10,1,0,1,0.01]
solver = ["newton-cg","lbfgs","liblinear","sag","saga","newton-cholesky"]

In [17]:
params = dict(penalty = penalty, C = c_values, solver = solver)

In [18]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1, 0, 1, 0.01],
 'solver': ['newton-cg',
  'lbfgs',
  'liblinear',
  'sag',
  'saga',
  'newton-cholesky']}

In [19]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold

In [20]:
cv = StratifiedKFold()

In [21]:
grid = GridSearchCV(estimator=model,param_grid=params, cv=cv, scoring="accuracy",n_jobs=-1)

In [22]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0, 1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [23]:
grid.fit(X_train,y_train)

/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/caferkosker/o

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0, 1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [24]:
grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}

In [25]:
 grid.best_score_

0.8233333333333335

In [26]:
y_pred = grid.predict(X_test)

In [27]:
score = accuracy_score(y_pred,y_test)
print("score: ",score)
print(classification_report(y_pred,y_test))
print("Confusion Matrix: \n", confusion_matrix(y_pred,y_test))

score:  0.7757142857142857
              precision    recall  f1-score   support

           0       0.85      0.77      0.81       247
           1       0.72      0.80      0.75       216
           2       0.76      0.76      0.76       237

    accuracy                           0.78       700
   macro avg       0.78      0.78      0.78       700
weighted avg       0.78      0.78      0.78       700

Confusion Matrix: 
 [[191  18  38]
 [ 26 172  18]
 [  7  50 180]]


In [28]:
#one vs rest

In [29]:
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier

In [30]:
onevsonemodel = OneVsOneClassifier(LogisticRegression())

In [31]:
onevsrestmodel = OneVsRestClassifier(LogisticRegression())

In [32]:
onevsonemodel.fit(X_train,y_train)
y_pred = onevsonemodel.predict(X_test)
score = accuracy_score(y_pred,y_test)
print("score: ",score)
print(classification_report(y_pred,y_test))
print("Confusion Matrix: \n", confusion_matrix(y_pred,y_test))

score:  0.7857142857142857
              precision    recall  f1-score   support

           0       0.84      0.81      0.83       234
           1       0.72      0.79      0.75       219
           2       0.80      0.77      0.78       247

    accuracy                           0.79       700
   macro avg       0.79      0.79      0.79       700
weighted avg       0.79      0.79      0.79       700

Confusion Matrix: 
 [[189  20  25]
 [ 25 172  22]
 [ 10  48 189]]


In [33]:
onevsrestmodel.fit(X_train,y_train)
y_pred = onevsrestmodel.predict(X_test)
score = accuracy_score(y_pred,y_test)
print("score: ",score)
print(classification_report(y_pred,y_test))
print("Confusion Matrix: \n", confusion_matrix(y_pred,y_test))

score:  0.7785714285714286
              precision    recall  f1-score   support

           0       0.83      0.81      0.82       232
           1       0.73      0.78      0.75       225
           2       0.78      0.75      0.76       243

    accuracy                           0.78       700
   macro avg       0.78      0.78      0.78       700
weighted avg       0.78      0.78      0.78       700

Confusion Matrix: 
 [[187  13  32]
 [ 29 175  21]
 [  8  52 183]]
